# Generated by Django 5.0.4 on 2024-04-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.CharField(db_comment='Owner ID', max_length=36, primary_key=True, serialize=False)),
                ('contact_id', models.CharField(db_comment='Contact ID', max_length=36)),
                ('fname', models.CharField(db_comment='First name', max_length=64)),
                ('lname', models.CharField(db_comment='Last name', max_length=64)),
                ('status', models.CharField(db_comment='Status', max_length=5)),
                ('crtu', models.CharField(db_comment='Creation User', max_length=64)),
                ('crtd', models.DateTimeField(db_comment='Creation Stamp')),
                ('updu', models.CharField(db_comment='Modification User', max_length=64)),
                ('updd', models.DateTimeField(db_comment='Modification Stamp')),
            ],
            options={
                'db_table': 'owner',
                'db_table_comment': 'Owners',
                'managed': False,
            },
        ),
    ]
