# Generated by Django 5.0.4 on 2024-04-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(db_comment='Contact ID', max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(db_comment='Status', max_length=5)),
                ('address1', models.CharField(max_length=128)),
                ('address2', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('zip', models.CharField(max_length=32)),
                ('phone1', models.CharField(max_length=32)),
                ('phone2', models.CharField(max_length=32)),
                ('fax', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=128)),
                ('crtu', models.CharField(db_comment='Creation User', max_length=64)),
                ('crtd', models.DateTimeField(db_comment='Creation Stamp')),
                ('updu', models.CharField(db_comment='Modification User', max_length=64)),
                ('updd', models.DateTimeField(db_comment='Modification Stamp')),
            ],
            options={
                'db_table': 'contact',
                'db_table_comment': 'Contacts',
                'managed': False,
            },
        ),
    ]
