# Generated by Django 5.0.4 on 2024-04-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.CharField(db_comment='Applciation ID', max_length=36, primary_key=True, serialize=False)),
                ('desc_s', models.CharField(db_comment='Short description', max_length=32)),
                ('desc_l', models.CharField(db_comment='Long description', max_length=64)),
                ('crtu', models.CharField(db_comment='Creation User', max_length=64)),
                ('crtd', models.DateTimeField(db_comment='Creation Stamp')),
                ('updu', models.CharField(db_comment='Modification User', max_length=64)),
                ('updd', models.DateTimeField(db_comment='Modification Stamp')),
            ],
            options={
                'db_table': 'application',
                'db_table_comment': 'Applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.CharField(db_comment='Caption ID', max_length=36, primary_key=True, serialize=False)),
                ('caption', models.CharField(db_comment='Caption', max_length=255)),
                ('crtu', models.CharField(db_comment='Creation User', max_length=64)),
                ('crtd', models.DateTimeField(db_comment='Creation Stamp')),
                ('updu', models.CharField(db_comment='Modification User', max_length=64)),
                ('updd', models.DateTimeField(db_comment='Modification Stamp')),
            ],
            options={
                'db_table': 'caption',
                'db_table_comment': 'Languages',
                'managed': False,
            },
        ),
    ]
