# Generated by Django 5.0.4 on 2024-04-19 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.CharField(db_comment='Building ID', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='Building name', max_length=128, unique=True)),
                ('no', models.CharField(db_comment='Street number', max_length=32)),
                ('street', models.CharField(db_comment='Street name', max_length=128)),
                ('city', models.CharField(db_comment='City', max_length=128)),
                ('department', models.CharField(db_comment='Prov/State/Department', max_length=128)),
                ('country', models.CharField(db_comment='Country', max_length=128)),
                ('zip', models.CharField(db_comment='Postal code', max_length=32)),
                ('crtu', models.CharField(db_comment='Creation User', max_length=64)),
                ('crtd', models.DateTimeField(db_comment='Creation Stamp')),
                ('updu', models.CharField(db_comment='Modification USer', max_length=64)),
                ('updd', models.DateTimeField(db_comment='Modification Stamp')),
            ],
            options={
                'db_table': 'building',
                'db_table_comment': 'Buildings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.CharField(db_comment='Owner ID', max_length=36, primary_key=True, serialize=False)),
                ('contact_id', models.CharField(db_comment='Contact ID', max_length=36)),
                ('fname', models.CharField(db_comment='First name', max_length=64)),
                ('lname', models.CharField(db_comment='Last name', max_length=64)),
                ('status', models.CharField(db_comment='Status', max_length=5)),
                ('crtu', models.CharField(db_comment='Creation User', max_length=64)),
                ('crtd', models.DateTimeField(db_comment='Creation Stamp')),
                ('updu', models.CharField(db_comment='Modification User', max_length=64)),
                ('updd', models.DateTimeField(db_comment='Modification Stamp')),
            ],
            options={
                'db_table': 'owner',
                'db_table_comment': 'Owners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('building', models.OneToOneField(db_comment='Building ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='building.building')),
                ('year', models.CharField(db_comment='Year', max_length=4)),
                ('month_start', models.CharField(db_comment='Starting month (01, 02, etc)', max_length=2)),
                ('day_start', models.CharField(db_comment='Starting monthly day (01, 02, etc)', max_length=2)),
                ('num_periods', models.CharField(db_comment='Number of monthly periods', max_length=2)),
                ('crtu', models.CharField(db_comment='Creation User', max_length=64)),
                ('crtd', models.DateTimeField(db_comment='Creation Stamp')),
                ('updu', models.CharField(db_comment='Modification User', max_length=64)),
                ('updd', models.DateTimeField(db_comment='Modification Stamp')),
            ],
            options={
                'db_table': 'exercice',
                'db_table_comment': 'Accounting Exercices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('building', models.OneToOneField(db_comment='Building ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='building.building')),
                ('name', models.CharField(db_comment='Unit name', max_length=32)),
                ('active', models.CharField(db_comment='Active T/F', max_length=1)),
                ('crtu', models.CharField(db_comment='Creation User', max_length=64)),
                ('crtd', models.DateTimeField(db_comment='Creation Stamp')),
                ('updu', models.CharField(db_comment='Modification User', max_length=64)),
                ('updd', models.DateTimeField(db_comment='Modification Stamp')),
            ],
            options={
                'db_table': 'unit',
                'db_table_comment': 'Units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingOwner',
            fields=[
                ('building', models.OneToOneField(db_comment='Building ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='building.unit')),
                ('unit_name', models.CharField(db_comment='Unit name', max_length=32)),
                ('start_date', models.DateField(db_comment='Date From')),
                ('end_date', models.DateField(db_comment='Date To')),
                ('active', models.CharField(db_comment='Status', max_length=1)),
                ('crtu', models.CharField(db_comment='Creation User', max_length=64)),
                ('crtd', models.DateTimeField(db_comment='Creation Stamp')),
                ('updu', models.CharField(db_comment='Modification User', max_length=64)),
                ('updd', models.DateTimeField(db_comment='Modification Stamp')),
            ],
            options={
                'db_table': 'building_owner',
                'db_table_comment': 'Building Owners',
                'managed': False,
            },
        ),
    ]
